name: Sync Backend to Hugging Face Space

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push backend folder to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd backend

          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git add .
          git commit -m "deploy: sync from github main"

          git push --force https://syahrul11:$HF_TOKEN@huggingface.co/spaces/syahrul11/nutriguide-rag HEAD:main